### ISSUE TITLE
Compute log_probs with diffusion policy model

### ISSUE THREAD

**Issue by nuomizai** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#1]
Was it possible to compute the action log_probs with the diffusion policy model in your algorithm?

**Comment by Zhendong-Wang** [comment]
Hi there. the analytical form of action log_probs is intractable, due to the non-linear transformation of neurual networks. Appoximation for the log prob could be found https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/losses.py#L50.
