### ISSUE TITLE
The problem about main.py on Windows10

### ISSUE THREAD

**Issue by HenryZhang-git** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#10]
Hi,Wang.I'm sorry to bother you again.After configuring the RL environment for Windows10, I ran the command  `python main.py --env_name walker2d-medium-expert-v2 --device 0 --ms offline --lr_decay --early_stop`.The Miniforge(cmd) showed me that
 `Traceback (most recent call last):
  File "main.py", line 235, in <module>
    os.makedirs(results_dir)
  File "D:\Mamba\envs\DP_RL\lib\os.py", line 223, in makedirs
    mkdir(name,mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'results\\walker2d-medium-expert-v2|exp_1|diffusion-ql|T-5|lr_decay|ms-offline|k-1|0'`
I think this may be due to system issues that cause differences between OS packages.
Since I am not sure about the cause of the problem and there are no similar problems on the Internet, I would like to ask your opinions.
Thanks again for your help in answering my questions

**Comment by Zhendong-Wang** [comment]
I think it is something related to the file name requirement of Windows system. Maybe '|' or some characters is not permitedd to appear in the file name on Windows machines.

**Comment by HenryZhang-git** [comment]
Thanks for your reply!I will try my best to adjust code to run this project in Windows10.If I can run this project in Win10,I will tell you and help more persons run this project in Windows10！
