### ISSUE TITLE
2D bandit task

### ISSUE THREAD

**Issue by HenryZhang-git** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#18]
Hi,Zhendong
Could you share your bandit task for me.When I try to vis bandit result.I have a problem.

This is my email:    ray20010302@163.com

I really need it.Thanks!

**Comment by Zhendong-Wang** [comment]
Thanks for your interests. Sent.

**Comment by Zhendong-Wang** [comment]
Thanks for your interest! The toy code has been uploaded to this github and could be simply run with https://github.com/Zhendong-Wang/Diffusion-Policies-for-Offline-RL/blob/master/run_toy.sh.
