### ISSUE TITLE
2D Bandit Task

### ISSUE THREAD

**Issue by jonathanbrady88** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#5]
Thank you for your inspirational novel work and open sourcing of the code.  

Is there a possibility for you to upload the 2D bandit task? I tried to reproduce the toy experiment on my own, but I may have made a mistake. I was hoping to compare my implementation with the original one.

Thanks again for your outstanding contribution.

**Comment by Zhendong-Wang** [comment]
Sure! Could you send me an email and I will reponse to you with the toy example code. Currently this repository is for sharing the code for the main algorithm and reproducing the main results in the paper. The toy example code is not cleaned but I can share with you through emails.

**Comment by erdiphd** [comment]
Hi @Zhendong-Wang 
I would like to have the 2D bandit task codes. 
Here is my e-mail erdiphd@hotmail.com
