### ISSUE TITLE
Unable install D4RL,dm-control,mjrl

### ISSUE THREAD

**Issue by HenryZhang-git** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#7]
Hi,bro!When I check a list which named 'requirement',and I use 'pip install' to install d4rl,dm-control,mjrl,I I found that I couldn't open the web page such as https://github.com/rail-berkeley/d4rl@d842aa194b416e564e54b0730d9f934e3e32f854.It tell me that 'Not Found 404'.So, could you tell another method to install D4RL,dm-control and mjrl which matches the version of other packages?

**Comment by HenryZhang-git** [comment]
I use win10+mamba(conda),and when I install D4RL which I use another method,it tell these wrong

`Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import d4rl
  File "d:\d4rl\d4rl-master\d4rl\__init__.py", line 47, in <module>
    import d4rl.pointmaze_bullet
  File "d:\d4rl\d4rl-master\d4rl\pointmaze_bullet\__init__.py", line 1, in <module>
    from ..pointmaze.maze_model import OPEN, U_MAZE, MEDIUM_MAZE, LARGE_MAZE, U_MAZE_EVAL, MEDIUM_MAZE_EVAL, LARGE_MAZE_EVAL
  File "d:\d4rl\d4rl-master\d4rl\pointmaze\__init__.py", line 1, in <module>
    from .maze_model import MazeEnv, OPEN, U_MAZE, MEDIUM_MAZE, LARGE_MAZE, U_MAZE_EVAL, MEDIUM_MAZE_EVAL, LARGE_MAZE_EVAL
  File "d:\d4rl\d4rl-master\d4rl\pointmaze\maze_model.py", line 2, in <module>
    from gym.envs.mujoco import mujoco_env
  File "D:\Software\Mambaforge\envs\DP_RL\lib\site-packages\gym\envs\mujoco\__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "D:\Software\Mambaforge\envs\DP_RL\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 14, in <module>
    raise error.DependencyNotInstalled(
gym.error.DependencyNotInstalled: DLL load failed while importing cymj: 找不到指定的模块。. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)`

I'm a green hand in IT,Please tell me how to do.Thank you very much!!!

**Comment by Zhendong-Wang** [comment]
I think D4RL maybe changed their link for package installation. But you can always go to their github, https://github.com/Farama-Foundation/D4RL, for installing. If you are using win, I would recommend to use WSL to install the env in Linux, which could be easier. I didn't try to set up this environemnt in window.

**Comment by HenryZhang-git** [comment]
Do you mean to use Linux as much as possible for reinforcement learning directions？I found that so much environments are not compatible with Windows such as Spinning Up which is from OpenAI.
