### ISSUE TITLE
About train step

### ISSUE THREAD

**Issue by HenryZhang-git** [Zhendong-Wang/Diffusion-Policies-for-Offline-RL#9]
Hi,Wang,I have run your project in Ubuntu20.04 successfully,and I run this code you have mentioned `python main.py --env_name walker2d-medium-expert-v2 --device 0 --ms offline --lr_decay --early_stop`
Now,I want to know how many steps I should train the agent if I wanna get a better training effect.Or, could you tell me which file contains the largest training step.
Thank you!

**Comment by Zhendong-Wang** [comment]
It will print out the experiment log, and it usually converge very quickly and you will see the score around 1.1 (110%). The default is for training 2000 epochs, where epoch consists of 1000 training steps. Usually, 500 epochs you should see good results.

**Comment by HenryZhang-git** [comment]
Thanks for your reply!It is very helpful for me.
